name: Daily Execution of Main Script

on:
  push:
    branches: [ main,fix-ci ]
  schedule:
    - cron: '0 16 * * *'  # 每天北京时间 00:00（UTC 16:00）
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set Beijing Timezone
      uses: szenius/set-timezone@v1.2
      with:
        timezoneLinux: "Asia/Shanghai"

    # Check out repository under $GITHUB_WORKSPACE, so the job can access it
    - name: Checkout code
      uses: actions/checkout@v3

    # Run using Python 3.8 for consistency and aiohttp
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        architecture: 'x64'
        cache: 'pip'

    # 安装字体
    - name: Install Chinese Fonts
      run: |
        # matplotlib中文乱码，需要安装字体包
        sudo apt-get update
        sudo apt-get install -y fonts-wqy-zenhei fonts-wqy-microhei fonts-noto-cjk

    # Install dependencies with `pip`
    - name: Install requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt

    # Generate all statistics images
    - name: Spider data and dealwith
      run: |
        python3 --version
        python3 main.py
        python3 main_analyze.py
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXCLUDED: ${{ secrets.EXCLUDED }}
        EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
        EXCLUDE_FORKED_REPOS: true

    # Commit all changed files to the repository
    - name: Commit to the repo
      run: |
        echo 'Commit to the repo'
        git config --global user.name "yansheng836/bilibili-Fanrenpc"
        git config --global user.email "bilibili-Fanrenpc[bot]@yansheng836.github.io"
        # 兼容git status中文乱码问题
        git config --global core.quotepath false

        git status
        git add .
        # Force the build to succeed, even if no files were changed
        git commit -m 'Update generated files' || true
        git push